# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 47f9876c1f91be6940da5c70e5cba71b809062952586fff73d6290b820d2b57dcc9a1d45f749ed47f18da8d5bb49e29904bba708c32a565a9147d842d3d57ce2

test:
  secret_key_base: c2e788d11a84e7059ad128f486b851184cbbc376baf70d7e355435a07a8809aa720b9e19221e5292e4a144fcefa4c1ea16e2cbbec9020870ff3b68d0a2ff9b16

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
